auth_enabled: false

limits_config:
  max_entries_limit_per_query: 5000  # Add a valid key for limits, replace/remove unsupported ones.

server:
  http_listen_port: 3100

common:
  ring:
    instance_addr: 0.0.0.0
    kvstore:
      store: inmemory
  replication_factor: 1
  path_prefix: /tmp/loki

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper  # Updated for modern configurations.
      object_store: filesystem
      schema: v11            # Use a schema version your Loki supports.
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /tmp/loki/index
    shared_store: filesystem
  filesystem:
    directory: /tmp/loki/chunks
