version: "3"
services:
  server:
    build:
      context: ./voting-app-server
    container_name: voting-app-server
    ports:
      - "5000:5000"
    volumes:
      - server-data:/app/data
    depends_on:
      - redis
      - alloy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOY_URL=http://localhost:12345
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://localhost:3200
      - GRAPHITE_HOST=graphite # Add Graphite service name here
      - GRAPHITE_PORT=2003 # If you're sending metrics to Graphite Carbon port
    networks:
      - voting-app-network

  client:
    build:
      context: ./voting-app-client
    container_name: voting-app-client
    ports:
      - "3001:3001"
    volumes:
      - client-data:/usr/share/nginx/html
    networks:
      - voting-app-network

  redis:
    image: "redis:alpine"
    container_name: voting-app-redis
    ports:
      - "6379:6379"
    networks:
      - voting-app-network

  nginx:
    image: nginx:alpine
    container_name: voting-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - voting-app-network

  alloy:
    image: grafana/alloy:v1.0.0
    pull_policy: always
    restart: on-failure
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
    environment:
      REMOTE_WRITE_HOST: http://localhost:8080
      LOKI_HOST: http://localhost:3100
      TEMPO_HOST: http://localhost:4318
      PYROSCOPE_HOST: http://localhost:4040
    depends_on:
      - mimir
      - loki
      - tempo
      - pyroscope
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental # Enable all functionality
    ports:
      - "12345:12345"
    networks:
      - voting-app-network

  mimir:
    image: grafana/mimir:2.12.0
    restart: on-failure
    command:
      - -config.file=/etc/mimir-config/mimir-config.yaml
    volumes:
      - ./mimir-config.yaml:/etc/mimir-config/mimir-config.yaml
    ports:
      - "8080:8080"
    networks:
      - voting-app-network

  loki:
    image: grafana/loki:3.0.0
    restart: on-failure
    ports:
      - "3100:3100"

  tempo:
    image: grafana/tempo:2.4.1
    restart: on-failure
    command:
      - "-storage.trace.backend=local"
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"
      - "-auth.enabled=false"
      - "-server.http-listen-port=3200"
    ports:
      - "3200:3200"
      - "4317:4317"

  pyroscope:
    image: grafana/pyroscope:1.5.0
    restart: on-failure
    ports:
      - "4040:4040"

  graphite:
    image: graphiteapp/graphite-statsd:latest
    container_name: graphite
    ports:
      - "8081:80" # Graphite web interface
      - "2003-2004:2003-2004" # Graphite Carbon ports
      - "8125:8125/udp" # StatsD UDP port
      - "8126:8126"
    environment:
      - GRAPHITE_TIME_ZONE=UTC
    volumes:
      - graphite-data:/opt/graphite/storage
    networks:
      - voting-app-network

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    ports:
      - "8086:8086" # InfluxDB HTTP API
    volumes:
      - influxdb-data:/var/lib/influxdb
    environment:
      INFLUXDB_DB: mydb # Optional: Create a database on startup
      INFLUXDB_ADMIN_USER: "admin"
      INFLUXDB_ADMIN_PASSWORD: "password"

  influxdb_exporter:
    image: prom/influxdb-exporter
    container_name: influxdb_exporter
    ports:
      - "9122:9122"
    environment:
      INFLUXDB_URL: http://influxdb:8086
    depends_on:
      - influxdb
    networks:
      - voting-app-network

  # prometheus-to-graphite:
  #   image: prom/graphite-exporter
  #   container_name: prometheus-to-graphite
  #   ports:
  #     - "2005:2003" # Graphite port
  #   environment:
  #     - GRAPHITE_ADDR=graphite:2003 # Address of your Graphite instance
  #     - PROMETHEUS_URL=http://prometheus:9090 # Address of Prometheus
  #   networks:
  #     - voting-app-network

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090" # Prometheus web interface
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml # Prometheus config file
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    networks:
      - voting-app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    command:
      - --config=/etc/grafana-config/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana.ini:/etc/grafana-config/grafana.ini
    depends_on:
      - mimir
      - loki
      - tempo
      - graphite
      - prometheus
    networks:
      - voting-app-network

networks:
  voting-app-network:
    driver: bridge

volumes:
  server-data:
  client-data:
  graphite-data:
  influxdb-data:
