version: '3'
services:
  server:
    build:
      context: ./voting-app-server
    container_name: voting-app-server
    ports:
      - "5000:5000"
    volumes:
      - server-data:/app/data
    depends_on:
      - redis
      - alloy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - ALLOY_URL=http://alloy:12345
    networks:
      - voting-app-network

  client:
    build:
      context: ./voting-app-client
    container_name: voting-app-client
    ports:
      - "3001:3001"
    volumes:
      - client-data:/usr/share/nginx/html
    networks:
      - voting-app-network

  redis:
    image: "redis:alpine"
    container_name: voting-app-redis
    ports:
      - "6379:6379"
    networks:
      - voting-app-network

  nginx:
    image: nginx:alpine
    container_name: voting-app-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - client
      - server
    networks:
      - voting-app-network

  alloy:
    image: grafana/alloy:v1.0.0
    container_name: alloy
    ports:
      - 12345:12345
      - 4317:4317
    pull_policy: always
    restart: on-failure
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy
      - ./logs:/tmp/app-logs/
    environment:
      REMOTE_WRITE_HOST: http://mimir:9009
      LOKI_HOST: http://loki:3100
      TEMPO_HOST: http://tempo:3200
    depends_on:
      - mimir
      - loki
      - tempo
    command:
      - run
      - /etc/alloy/config.alloy
      - --storage.path=/var/lib/alloy/data
      - --server.http.listen-addr=0.0.0.0:12345
      - --stability.level=experimental
    networks:
      - voting-app-network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    command:
      - --config=/etc/grafana-config/grafana.ini
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/:/etc/grafana/provisioning
      - ./grafana.ini:/etc/grafana-config/grafana.ini
    depends_on:
      - mimir
      - loki
      - tempo
    networks:
      - voting-app-network

  mimir:
    image: grafana/mimir:latest
    container_name: mimir
    restart: on-failure
    volumes:
      - ./mimir-config.yaml:/etc/mimir/mimir.yaml
    command:
      - --config.file=/etc/mimir/mimir.yaml
    ports:
      - "9009:9009"
    networks:
      - voting-app-network

  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    restart: on-failure
    volumes:
      - ./loki-config.yaml:/etc/loki/loki.yaml
    ports:
      - "3100:3100"
    networks:
      - voting-app-network

  tempo:
    image: grafana/tempo:2.4.1
    container_name: tempo
    restart: on-failure
    command:
      - "-storage.trace.backend=local"                  
      - "-storage.trace.local.path=/tmp/tempo/traces"
      - "-storage.trace.wal.path=/tmp/tempo/wal"        
      - "-auth.enabled=false"
      - "-server.http-listen-port=3200"
    ports:
      - "3200:3200"
    networks:
      - voting-app-network

networks:
  voting-app-network:
    driver: bridge

volumes:
  server-data:
  client-data: