version: "3"

services:

  mythical-database:
    image: postgres:14.5
    restart: always
    environment:
      POSTGRES_PASSWORD: "mythical"
    volumes:
      - "postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - voting-app-network


  mythical-server:
    build:
      context: ./source
      dockerfile: ./Dockerfile
      args:
        SERVICE: mythical-beasts-server
    restart: always
    ports:
      - "5000:5000"
      - "80:80"
    depends_on:
      - mythical-database
    environment:
      - NAMESPACE=production
      - LOGS_TARGET=http://alloy:3100/loki/api/v1/push
      - TRACING_COLLECTOR_HOST=alloy
      - TRACING_COLLECTOR_PORT=4317
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
      - OTEL_RESOURCE_ATTRIBUTES=ip=1.2.3.5
    networks:
      - voting-app-network

  voting-app-client:
    build:
      context: ./voting-app-client
      dockerfile: ./Dockerfile
      args:
        SERVICE: voting-app-client
    restart: always
    ports:
      - "3001:3001"
    networks:
      - voting-app-network


  alloy:
    image: grafana/alloy:v1.3.1
    ports:
      - "12345:12345"
      - "12348:12348"
    volumes:
      - "./alloy/config.alloy:/etc/alloy/config.alloy"
      - "./alloy/endpoints.json:/etc/alloy/endpoints.json"
    command:
      [
        "run",
        "--server.http.listen-addr=0.0.0.0:12345",
        "--stability.level=public-preview",
        "/etc/alloy/config.alloy",
      ]
    networks:
      - voting-app-network

  loki:
    image: grafana/loki:3.2.0
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./loki/loki-config.yaml:/etc/loki/local-config.yaml
    command:
      [
        "--pattern-ingester.enabled=true",
        "-config.file=/etc/loki/local-config.yaml ",
      ]
    networks:
      - voting-app-network


  mimir:
    image: grafana/mimir:2.13.0
    container_name: mimir
    ports:
      - "9009:9009"
    volumes:
      - ./mimir/mimir-config.yaml:/etc/mimir/mimir-config.yaml
    command:
      [
        "-ingester.native-histograms-ingestion-enabled=true",
        "-config.file=/etc/mimir/mimir-config.yaml",
      ]
    networks:
      - voting-app-network


  tempo:
    image: grafana/tempo:2.6.0
    ports:
      - "3200:3200"
      - "4317:4317"
      - "4318:4318"
    command: ["-config.file=/etc/tempo-config.yaml"]
    volumes:
      - "./tempo/tempo-config.yaml:/etc/tempo-config.yaml"
    networks:
      - voting-app-network


  grafana:
    image: grafana/grafana:11.2.0
    volumes:
      - "./grafana/provisioning:/etc/grafana/provisioning"
      - "./grafana/grafana.ini:/etc/grafana/grafana.ini"
    ports:
      - "3000:3000"
    environment:
      - GF_FEATURE_TOGGLES_ENABLE=flameGraph traceqlSearch traceQLStreaming correlations metricsSummary traceqlEditor traceToMetrics traceToProfiles datatrails
      - GF_INSTALL_PLUGINS=grafana-lokiexplore-app,grafana-exploretraces-app
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - voting-app-network

networks:
  voting-app-network:
    driver: bridge

volumes:
  grafana:
  postgres:














