server:
  http_listen_port: 3200
  grpc_listen_port: 9095

distributor:
  receivers:
    otlp:
      protocols:
        http:
          enabled: true
        grpc:
          enabled: true
    query:
      http_listen_port: 4317
      grpc_listen_port: 4318
ingester:
  max_block_duration: 5m
  block_retention: 1h

compactor:
  compaction:
    block_retention: 1h

storage:
  trace:
    backend: local
    wal:
      path: /tmp/tempo/wal
    local:
      path: /tmp/tempo/blocks

overrides:
  defaults:
    metrics_generator:
      processors: [service-graphs, span-metrics]

querier:
  frontend_address: "tempo:9095"  
  timeout: 10s  
  max_concurrent_queries: 20
  cache:
    enabled: true
    ttl: 10m

querier.frontend:
  grpc_address: "alloy:4318"  
  http_address: "alloy:12345"  
  max_cache_size: 100MB  
  query_timeout: 10s  
  max_concurrent_queries: 20  
